# 一、简答题
- 如何理解js异步编程？
> js是一个单线程的，只能一个一个的处理任务，当遇到多任务的情况下可能会导致阻塞。效率低，任务时间长  
> 异步编程则可以高效的处理任务，提高了效率和执行率。
- EventLoop、消息队列都是做什么的？
> 1. eventloop是一个事件循环机制，主程序从消息队列中读取事件，不断循环  
> 2. 消息队列是存放异步任务的一个地方，等待主线程执行完同步任务，然后从消息队列中依次取出异步任务，放入调用站中执行  
- 什么是宏任务、什么是微任务？
> setTimeout、setInterval、setImmediate  是宏任务
> process.nextTick  是微任务
>  微任务的处理优先级高于宏任务
- 代码
> 一、将下面异步代码使用 Promise 的方式改进
```
new Promise(function(resolve,rejects){
    var a = 'hello'
    resolve(a)
    rejects('err')
}).then(function(res){
        var b = 'lagou'
        return res + b
    // resolve(res + b)
}).then(function(res){
    var c = 'I ❤️ U'
    console.log(res + c)
})
```   
> 二、基于以下代码完成下面的四个练习   
> 练习1：使用组合函数 fp.flowRight() 重新实现下面这个函数
```
var a = fp.flowRight(fp.prop('in_stock'),fp.last)
```  
> 练习2:使用 fp.flowRight()、fp.prop() 和 fp.first() 获取第一个 car 的 name
```
var a = fp.flowRight(fp.prop('name'),fp.first)
```  
> 练习3：使用帮助函数 _average 重构 averageDollarValue，使用函数组合的方式实现
```
const  _average = function (xs){
    return fp.reduce(fp.add,0,xs) / xs.length
}
const dollar_value = function(array){
    return fp.map(car=>car.dollar_value)
}
const a = fp.flowRight(_average,dollar_value(cars))
```  
> 练习4：使用 flowRight 写一个 sanitizeNames() 函数，返回一个下划线连续的小写字符串，把数组中的 name 转换为这种形式，例如：sanitizeNames(["Hello World"]) => ["hello_world"]
```
let word = ['hello world']
let change = fp.replace(/\W+/g,"_") 
const sanitizeNames = fp.flowRight(fp.map(word=>change(word)))

```
> 三、基于下面提供的代码，完成后续的四个练习   
> 练习1：使用 fp.add(x, y) 和 fp.map(f,x) 创建一个能让 functor 里的值增加的函数 ex1
```
const fp = require('lodash/fp')
const {Maybe, Container} = require('./support')
let maybe = Maybe.of([5,6,1])
let ex1 = (num) => {
    // 你需要实现的函数。。。
    let cont = fp.flowRight(fp.map(fp.add(num)))
    return maybe.map(cont) 
}
```
> 练习2：实现一个函数 ex2，能够使用 fp.first 获取列表的第一个元素   
```
let xs = Container.of(['do','ray','me','fa','so','la','ti','do'])
let ex2 = () => {
    //你要实现的函数
	return xs.map(fp.first)._value
}
```
> 练习3：实现一个函数 ex3，使用 safeProp 和 fp.first 找到 user 的名字的首字母   
```
 //const fp = require('lodash/fp')
 //const {Maybe, Container} = require('./support')
let safeProp = fp.curry(function(x, o){
    return Maybe.of(o[x])
})
let user = { id: 2, name: 'Albert' }
let ex3 = () => {
    // 你需要实现的函数。。。
  return safeProp('name',user).map(fp.first)._value
}
``` 
> 练习4：使用 Maybe 重写 ex4，不要有 if 语句   
```
let  ex4 = function(n){
    let m1 = new MayBe(n)
    let m2 = m1.map(parseInt)
    return m2._value
}
```
> 四、手写实现 MyPromise 源码  
```
/**
 * 1、promise是一个类，在执行这个类的时候，需要传递一个执行器进去，执行器会立即执行
 * 2、Promise中有三个状态，分别为 成功 resolve、失败 reject、等待 pedding
 *    状态一旦确定就不能被改变
 *    pedding-resolve
 *    pedding-reject
 * 3、resolve和reject函数是用来更改状态的
 *    resolve:fufilled
 *    reject:rejected
 * 4、then方法做的事情就是判断状态，如果状态是成功，调用成功回调函数，如果是失败，调用失败函数，then方法是被定义在原型对象中
 * 5、then成功回调有一个参数，表示成功之后的值，失败回调有一个参数，表示失败的原因
 */
const PEDDING = 'pedding' //等待
const FUFILLED = 'fufilled' //成功
const REJECT = 'reject' //失败

class MyPromise {
    constructor(exeuctor) {
        try {
            exeuctor(this.resolve, this.reject)
        } catch (error) {
            this.reject(error)
        }
    }

    status = PEDDING
    //成功之后的值
    value = undefined
    //失败之后的原因
    reason = undefined
    //成功回调
    // successCallback = undefined  只能处理一个回调函数
    successCallback = []
    //失败回调
    // failCallback = undefined
    failCallback = []


    //使用箭头函数定义是为了执行方法的时候让this指向MyPromise的实例对象
    resolve = value => {
        //如果状态不是等待，向下执行
        if (this.status !== PEDDING) return
        this.status = FUFILLED
        //保存成功之后的值
        this.value = value
        //判断成功回调是否存在，如果存在则调用
        // this.successCallback && this.successCallback(this.value)
        while (this.successCallback.length) {
            // this.successCallback.shift()(this.value)
            this.successCallback.shift()()
        }
    }

    reject = reason => {
        if (this.status !== PEDDING) return
        this.status = REJECT
        //保存失败后的原因
        this.reason = reason
        // this.failCallback && this.failCallback(this.reason)
        while (this.failCallback.length) {
            // this.failCallback.shift()(this.reason)
            this.failCallback.shift()()
        }
    }

    then(successCallback, failCallback) {
        successCallback = successCallback ? successCallback : value => value
        failCallback = failCallback ? failCallback : reason => { throw reason }
        let promise2 = new MyPromise((resolve, reject) => {
            if (this.status === FUFILLED) {
                // let x = successCallback(this.value)
                /**
                 * 需要判断x的值是普通值还是promise对象,如果是普通值，直接调用resolve，
                 * 如果是promise对象，查看promise的结果，根据promise对象返回的结果决定调用resolve，reject
                 */
                // resolvePromise(x,resolve,reject)
                //防止循环调用,但是此时promise2并不能获取到，所以现在需要使其变成异步执行代码
                // resolvePromise(promise2,x,resolve,reject)
                //使用try-catch捕获异常
                try {
                    setTimeout(() => {
                        let x = successCallback(this.value)
                        resolvePromise(promise2, x, resolve, reject)
                    }, 0)
                } catch (error) {
                    reject(error)
                }
            } else if (this.status === REJECT) {
                setTimeout(() => {
                    let x = failCallback(this.reason)
                    resolvePromise(promise2, x, resolve, reject)
                }, 0)
            } else {
                //状态为pedding，等待
                // 将成功回调和失败回调存储起来
                // this.successCallback.push(successCallback)
                this.successCallback.push(() => {
                    setTimeout(() => {
                        let x = successCallback(this.value)
                        resolvePromise(promise2, x, resolve, reject)
                    }, 0)
                })
                // this.failCallback.push(failCallback)
                this.failCallback.push(() => {
                    setTimeout(() => {
                        let x = failCallback(this.value)
                        resolvePromise(promise2, x, resolve, reject)
                    }, 0)
                })
            }
        })
        return promise2
    }

    finally(callback){
        return this.then(value=>{
            return MyPromise.resolve(callback()).then(()=>value)
        },reason=>{
            return MyPromise.resolve(callback()).then(()=>{throw reason})
        })
    }

    catch(failCallback){
        return this.then(undefined,failCallback)
    }


    static all(array) {
        let result = []
        
        return new MyPromise((resolve, reject) => {
            let count = 0
            function addData(index,value){
                result[index] = value
                count++
                console.log(count,array.length)
                if(count === array.length){
                    resolve(result) 
                }   
            }
            for(let i= 0;i<array.length;i++){
                let current = array[i]
                if(current instanceof MyPromise){
                    //Promise对象
                    current.then((value)=>{
                        addData(i,value)
                    },(reason)=>{
                        reject(reason)
                    })
                }else{//普通值
                    addData(i,current)
                }
            }
        })
    }


    static resolve(value){
        if(value instanceof MyPromise){
            return value
        }
        return new MyPromise(resolve=>resolve(value))
    }

}

function resolvePromise(promise, x, resolve, reject) {
    if (promise === x) {
        return reject(new TypeError("Chaining cycle detected for promise #<Promise>    "))
    }
    if (x instanceof MyPromise) {
        x.then(resolve, reject)
    } else {
        resolve(x)
    }
}

module.exports = MyPromise

```













